name: Build and Deploy
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout  ️
        uses: actions/checkout@v2.3.1

      - name: lock npm version
        uses: actions/setup-node@v3
        with:
          node-version: 16.18.0

      - name: Install and Build
        run: |
          npm i -g pnpm@8.5.1
          pnpm run init
          pnpm run build:doc
        env:
          NODE_OPTIONS: '--max_old_space_size=4096'

      - name: test
        run: |
          pnpm run test

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.3
        with:
          branch: gh-pages
          folder: dist
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
